{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "lsm-storage.fullname" . }}-backend
  labels:
    {{- include "lsm-storage.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "lsm-storage.backendSelectorLabels" . | nindent 6 }}
{{- end }}
